### PR TITLE
Update adventure library to v5

### PR DESCRIPTION
**Pull request by TheDejavu**
The problem is in `CommandResponseHandler`, which builds a static prefix component on class load. In Adventure 4, `build()` returned `BuildableComponent`. In Adventure 5, it returns `Component`.

This PR fixes that by recompiling against Adventure 5.1.1, which is what Paper 26.2 actually ships.

Related Paper issue: https://github.com/PaperMC/Paper/issues/13966

## What changed

- Bumped `spark-common` from Adventure 4.21.0 to the Adventure 5.1.1 BOM
- Set `spark-common` to compile with Java 21
- Set `spark-paper` to compile with Java 25, matching Paper 26.2
- Updated the Paper API dependency to `26.2.build.29-alpha`

## How I tested it

- [x] Built `spark-paper` locally and published it to Maven local
- [x] Built Paper 26.2 against that Spark build
- [x] Started a server and confirmed Spark loads without the `NoSuchMethodError`
- [x] Verified the background profiler starts and `/spark` commands works normally

### CODE REVIEW

**Comment by lucko** [comment]
Not massively keen to do this unless it's absolutely necessary, spark runs on other adventure v4 platforms like Sponge, Velocity, which haven't updated yet. I believe adventure v5 was meant to be binary compatible with v4, in which case this is an adventure bug.

**Comment by TheDejavu** [comment]
Fair point — if v5 is meant to be binary compatible, this is on Adventure. But [adventure#1431](https://github.com/PaperMC/adventure/issues/1431) shows the ABI bridge from [#1407](https://github.com/PaperMC/adventure/pull/1407) still doesn't fix `Component.text().build()` on 5.1.1 / Paper 26.2. Spark hits the same thing via a static initializer in `CommandResponseHandler`. Unless that gets fixed upstream and into 26.2, recompiling against v5 is the only way Spark loads on Paper today. Happy to limit the Adventure 5 bump to `spark-paper` so Velocity/Sponge stay on v4.

**Comment by lucko** [comment]
The issue has been fixed in adventure.
